trigger:
  branches:
    include:
      - main
      - master

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              Dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              tags: |
                $(tag)
      - job: ValidateTemplates
        displayName: Validate templates
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "test07-srvconnection"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: az group deployment validate --resource-group test07 --template-file $(Build.SourcesDirectory)/infrastructure.bicep

  - stage: Deploy
    jobs:
      - job: DeployInfrastructure
        displayName: "Deploy Infrastructure using ARM/Bicep"
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "test07-srvconnection"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: az deployment group create --resource-group test07 --template-file $(Build.SourcesDirectory)/infrastructure.bicep
            displayName: "Deploy Infrastructure"
      - job: DeployApp
        displayName: "Deploy Application to Azure App Service"
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "test07-srvconnection"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az webapp deployment source config-zip --resource-group test07 --name test07-appsrv --src $(System.DefaultWorkingDirectory)/azureserver
